name: Deploy to Heroku

on:
  push:
    branches:
      - master  # master branch'ına push yapıldığında tetiklenir.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Kullanmak istediğiniz Node.js versiyonunu belirtin.

      - name: Install dependencies
        run: |
          npm install

      - name: Log in to Heroku
        uses: akshnz/heroku-cli-action@v2
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}  # Heroku API anahtarını kullanıyoruz.

      - name: Deploy to Heroku
        run: |
          git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
          git push heroku master

